language: java
jdk:
  - openjdk8

stages:
  - tests-package-sonar
  - deploy

jobs:
  include:
    - stage: tests-package-sonar
      addons:
        sonarcloud:
          organization: "thepracticaldeveloper"
      script:
        - mvn clean package sonar:sonar
    - stage: deploy
      script: echo "Deploying..."
      deploy:
        provider: releases
        api_key: "${GITHUB_OAUTH_TOKEN}"
        file: "./target/quboo-sonar-plugin.jar"
        skip_cleanup: true
        on:
          tags: true
