version: "2"

services:
  sonar:
    image: sonarqube-quboo:latest
    ports:
      - '9000:9000'
      - '9092:9092'
    networks:
      - network-sonar
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      #      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres:10.5-alpine
    ports:
      - '5432:5432'
    networks:
      - network-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  network-sonar:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  #  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
